set -g @gruvbox_fg "#d4be98"
set -g @gruvbox_bg "#32302f"
set -g @gruvbox_red "#ea6962"
set -g @gruvbox_orange "#e78a4e"
set -g @gruvbox_yellow "#d8a657"
set -g @gruvbox_green "#a9b665"
set -g @gruvbox_aqua "#89b482"
set -g @gruvbox_blue "#7daea3"
set -g @gruvbox_purple "#d3869b"
set -g @gruvbox_gray "#504945"
set -g @gruvbox_dark_gray "#3c3836"
set -g @gruvbox_light_gray "#665c54"
