# Which is equivalent to
# format = '$all$directory$character'
add_newline = true

format = """$read_only$directory$character"""

right_format = "$hostname$git_branch$time"

[character]
success_symbol = '[➜ ](bold green)'

[gcloud]
